### ISSUE TITLE
Project Wikimedia - Create all wikis on Wikimedia

### ISSUE THREAD

**Issue by Hans5958** [Hans5958/PreMiD-Presences-Personal#1]
Continuation of Hans5958/PreMiD-Presences-Personal-Old#3

## Preface

Project Wikimedia is a project to create all presence for all Wikimedia/Wikimedia Foundation projects/wikis, along with other subdomains that is not a wiki.

### Presence List

Based on https://meta.wikimedia.org/wiki/Wikimedia_projects and https://meta.wikimedia.org/wiki/Complete_list_of_Wikimedia_projects.

- [x] [Wikipedia](https://www.wikipedia.org/)
  - [x] [Nostalgia](https://nostalgia.wikipedia.org/)
  - [x] [Test Wiki](https://test.wikipedia.org/wiki/)
  - [x] [Test 2 Wiki](https://test2.wikipedia.org/wiki/)
  - [x] [Wikipedia Ten](https://ten.wikipedia.org)
- [x] [Wikitionary](https://www.wiktionary.org/)
- [x] [Wikiquote](https://www.wikiquote.org/)
- [x] [Wikibooks](https://www.wikibooks.org/)
- [x] [Wikisource](https://wikisource.org/) (wikisource.org also a wiki)
- [x] [Wikinews](https://www.wikinews.org/)
- [x] [Wikiversity](https://www.wikiversity.org/)
  - [x] [Wikiversity Beta](https://beta.wikiversity.org/)
- [x] [Wikivoyage](https://www.wikivoyage.org/)
- [x] [Wikispecies](https://species.wikimedia.org/)
- [x] [Wikimedia Commons](https://commons.wikimedia.org/)
  - [x] [Test Wikimedia Commons](https://test-commons.wikimedia.org/)
- [x] [Wikidata](https://www.wikidata.org/) (single language)
  - [x] [Test Wikidata](https://test.wikidata.org/)
- [x] Wikimedia (anything that is not in the content project category)

### Overview

- [x] Phase 1 - Completing Wikipedia
- [x] Phase 2 - All The Wikis
- [x] Phase 3 - Wikimedia Presence

### Phase 1 - Completing Wikipedia

- [x] Add support for test and the "10" subdomains
- [x] Add language on the state field
- [x] Test and screenshot for PR
- [x] Prepare PR body
- [x] Do final changes
- [x] Submit pull request
- [x] Do requested changes (if necessary)
- [x] Merge branch

### Phase 2 - All The Wikis

- [x] Prepare files and folders
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Prepare assets
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Set Discord application and Imgur links
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Set metadata
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Change necessary code based on Wikipedia
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Test and screenshot for PR
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Prepare PR body
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Do final changes
- [x] Submit pull request
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata
- [x] Do requested changes (if necessary)
- [x] Merge branch
  - [x] Wikitionary
  - [x] Wikiquote
  - [x] Wikibooks
  - [x] Wikisource
  - [x] Wikinews
  - [x] Wikiversity
  - [x] Wikivoyage
  - [x] Wikispecies
  - [x] Wikimedia Commons
  - [x] Wikidata

### Phase 3 - Wikimedia Presence

- [x] Prepare files and folders
- [x] Prepare assets
- [x] Set Discord application and Imgur links
- [x] Set metadata
- [x] Code the presence
  - [x] Change necessary code based on Wikipedia
  - [x] Start from scratch
- [x] Test and screenshot for PR
- [x] Prepare PR body
- [x] Do final changes
- [x] Submit pull request
- [x] Do requested changes (if necessary)
- [x] Merge branch
