### ISSUE TITLE
Project Wikimedia - Create all wikis on Wikimedia (and some other sites)

### ISSUE THREAD

**Issue by Hans5958** [Hans5958/PreMiD-Presences-Personal#3]
## Preface

Project Wikimedia is a project to create all presence for all Wikimedia/Wikimedia Foundation domains and subdomains.

### Presence List

Based on https://meta.wikimedia.org/wiki/Wikimedia_projects and https://meta.wikimedia.org/wiki/Complete_list_of_Wikimedia_projects.

- [ ] [Wikipedia](https://www.wikipedia.org/)
  - [ ] [Nostalgia](https://nostalgia.wikipedia.org/)
  - [ ] [Test Wiki](https://test.wikipedia.org/wiki/)
  - [ ] [Test 2 Wiki](https://test2.wikipedia.org/wiki/)
  - [ ] [Wikipedia Ten](https://ten.wikipedia.org)
- [ ] [Wikitionary](https://www.wiktionary.org/)
- [ ] [Wikiquote](https://www.wikiquote.org/)
- [ ] [Wikibooks](https://www.wikibooks.org/)
- [ ] [Wikisource](https://wikisource.org/) (wikisource.org also a wiki)
- [ ] [Wikinews](https://www.wikinews.org/)
- [ ] [Wikiversity](https://www.wikiversity.org/)
  - [ ] [Wikiversity Beta](https://beta.wikiversity.org/)
- [ ] [Wikivoyage](https://www.wikivoyage.org/)
- [ ] [Wikispecies](https://species.wikimedia.org/)
- [ ] [Wikimedia Commons](https://commons.wikimedia.org/)
  - [ ] [Test Wikimedia Commons](https://test-commons.wikimedia.org/)
- [ ] [Wikidata](https://www.wikidata.org/) (single language)
  - [ ] [Test Wikidata](https://test.wikidata.org/)
- [ ] [Incubator](https://incubator.wikimedia.org/)
- [ ] Wikimedia (anything that is not in the content project category)
  - [ ] [www](https://www.wikimedia.org/)
  - [ ] [Meta-wiki](https://meta.wikimedia.org/)
  - [ ] [Wikitech](https://wikitech.wikimedia.org/)
  - [ ] [Foundation](https://foundation.wikimedia.org/)
  - [ ] [MediaWiki](https://www.mediawiki.org/)
  - [ ] [Wikimedia Outreach](https://outreach.wikimedia.org/)
  - [ ] [Wikimania](https://wikimania.wikimedia.org/)
    - [ ] Including past years
  - [ ] [Wikimedia Strategic Planning](https://strategy.wikimedia.org/)
  - [ ] [Wikimedia Usability](https://usability.wikimedia.org)
  - [ ] [Login Wiki](https://login.wikimedia.org/)
  List below are not wikis.
  - [ ] [Wikimedia Foundation](https://wikimediafoundation.org/)
  - [ ] [Maliling List](https://lists.wikimedia.org/)
  - [ ] [Wikistats](https://stats.wikimedia.org/)
  - [ ] [Phabricator](https://phabricator.wikimedia.org/)
  - [ ] [Wikimedia Downloads](https://dumps.wikimedia.org/)

### Overview

- [ ] Phase 1 - Completing Wikipedia
- [ ] Phase 2 - All The Wikis
- [ ] Phase 3 - Wikimedia Presence

### Phase 1 - Completing Wikipedia

- [ ] Add support for test and 10 subdomains
- [ ] Add language on the state field
- [ ] Test and screenshot for PR
- [ ] Do final changes
- [ ] Submit pull request
- [ ] Do requested changes (if necessary)
- [ ] Merge branch

### Phase 2 - All The Wikis

- [ ] Prepare files and folders
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Prepare assets
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Set Discord application and Imgur links
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Set metadata
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Change necessary code based on Wikipedia
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Test and screenshot for PR
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Prepare PR body
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Do final changes
- [ ] Submit pull request
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator
- [ ] Do requested changes (if necessary)
- [ ] Merge branch
  - [ ] Wikitionary
  - [ ] Wikiquote
  - [ ] Wikibooks
  - [ ] Wikisource
  - [ ] Wikinews
  - [ ] Wikiversity
  - [ ] Wikivoyage
  - [ ] Wikispecies
  - [ ] Wikimedia Commons
  - [ ] Wikidata
  - [ ] Incubator

### Phase 3 - Wikimedia Presence

- [ ] Prepare files and folders
- [ ] Prepare assets
- [ ] Set Discord application and Imgur links
- [ ] Set metadata
- [ ] Change necessary code based on Wikipedia
- [ ] Test and screenshot for PR
- [ ] Prepare PR body
- [ ] Do final changes
- [ ] Submit pull request
- [ ] Do requested changes (if necessary)
- [ ] Merge branch

**Comment by Hans5958** [comment]
**FYI**: 

The Wikibooks PR is merged in two hours and six minutes (2h06m), one of the fastest, if not the fastest, pull request to be merged.
